name: Build and Release Hyprland Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        arch: [x86_64]
        # arch: [x86_64, x86_64-musl]
    runs-on: ubuntu-22.04
    env:
      XBPS_ALLOW_RESTRICTED: "yes"
      REPO_OWNER: "${{ github.repository_owner }}"
      REPO_NAME: "${{ github.event.repository.name }}"
      XBPS_TARGET_ARCH: ${{ matrix.arch }}
      PACKAGES_FILE: "packages.tar.gz"
      # XBPS_PASSPHRASE: ${{ secrets.SIGN_PASS }}

    steps:
      - name: checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v4
        with:
          ref: main
          path: ${{ env.REPO_NAME }}

      - name: checkout void-packages
        uses: actions/checkout@v4
        with:
          repository: void-linux/void-packages
          ref: master
          path: void-packages

      - name: copy
        run: |
          cat ${{ env.REPO_NAME }}/common/shlibs >> void-packages/common/shlibs
          cp -rv ${{ env.REPO_NAME }}/srcpkgs/* void-packages/srcpkgs

      - name: prepare xbps-static
        run: |
          mkdir -p /opt/xbps
          curl -LO http://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz
          tar xvf xbps-static-latest.x86_64-musl.tar.xz -C /opt/xbps
          rm xbps-static-latest.x86_64-musl.tar.xz

      # - name: free space
      #   run: |
      #     sudo rm -rf /usr/share/dotnet
      #     sudo rm -rf /usr/local/lib/android
      #     sudo rm -rf /opt/ghc
      #     sudo rm -rf /opt/hostedtoolcache/CodeQL

      - name: set path
        run: |
          echo "/opt/xbps/usr/bin/" >> $GITHUB_PATH

      - name: setup binray bootstrap
        working-directory: void-packages
        run: |
          ./xbps-src -m masterdir-${{ matrix.arch }} -A ${{ matrix.arch }} binary-bootstrap

      - name: build packages
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} swayosd
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprcursor

      - name: show built packages
        working-directory: void-packages/hostdir/binpkgs/
        run: |
          ls -la

      - name: compress Packages
        working-directory: void-packages/hostdir/binpkgs
        run: |
          tar -czvf ${{ env.PACKAGES_FILE }} *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:  
          name: ${{ env.REPO_NAME }}
          path: void-packages/hostdir/binpkgs/${{ env.PACKAGES_FILE }}

      # - name: build hyprutils
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprutils


      # - name: build hyprcursor
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprcursor

      # - name: build hyprwayland-scanner
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprwayland-scanner

      # - name: build aquamarine
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} aquamarine

      # - name: build hyprland
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprland

      # - name: build hyprland-protocols
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprland-protocols

      # - name: build xdg-desktop-portal-hyprland
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} xdg-desktop-portal-hyprland

      # - name: build hypridle
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hypridle

      # - name: build hyprlock
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprlock

      # - name: build hyprpaper
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprpaper

      # - name: build swayosd
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} swayosd

      # - name: build rofi wayland
      #   working-directory: void-packages
      #   run: |
      #     ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} rofi-wayland

      # - name: sign
      #   working-directory: void-packages/hostdir/binpkgs/
      #   run: |
      #     ls -la
      #     echo "${{ secrets.PRIV_KEY }}" > private.pem
      #     xbps-rindex --privkey private.pem --sign --signedby "${{ env.REPO_NAME }}-github-action" $PWD
      #     xbps-rindex --privkey private.pem --sign-pkg *.xbps

      # - name: checksum
      #   working-directory: void-packages/hostdir/binpkgs/
      #   run: |
      #     for file in *.xbps; do
      #       sha256sum "$file" | cut -d ' ' -f 1 > "${file}.sha256sum"
      #       sha512sum "$file" | cut -d ' ' -f 1 > "${file}.sha512sum"
      #     done

      # - name: release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       void-packages/hostdir/binpkgs/*.xbps
      #       void-packages/hostdir/binpkgs/*.sha256sum
      #       void-packages/hostdir/binpkgs/*.sha512sum
      #       void-packages/hostdir/binpkgs/*.sig2
      #       void-packages/hostdir/binpkgs/*repodata
